clean:
	rm -rf *o main

# We need the OpenNI SDK Directory
# This directory is in /usr/local/include/openni-2.2/Include
all:
	g++ -Wall -O3 -I /usr/local/include/openni-2.2/Include \
		-L /home/bryant/projectdoll/kinect_modeling main.cpp -o main


